// Transactions
export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS'
export const CREATE_TRANSACTION = 'CREATE_TRANSACTION'
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION'
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION'